<?php

namespace Umbrella\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserproductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserproductsRepository extends EntityRepository
{
}
