security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Umbrella\ShopBundle\Entity\User: 
            algorithm: md5
            encode-as-base64: false
            iterations: 2

        
    providers:
        main:
            entity: { class: Umbrella\ShopBundle\Entity\User, property: username }
            
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            
        main:
            pattern:  ^/.*
            form_login:
                check_path: _security_check
                login_path: _security_login
            logout:
                path:   _security_logout
                target: /
            #anonymous: true  

   

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
