security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Umbrella\ShopBundle\Entity\User: 
            algorithm: md5
            encode-as-base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    ivan:  { password: ivan, roles: [ 'ROLE_USER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern:  ^/login$
            security: false
        
        #welcome:
            #pattern:  ^/
            #security: false
            #anonymous: true    
            
        main:
            pattern:  ^/.*
            form_login:
                check_path: _security_check
                login_path: _security_login
            logout:
                path:   _security_logout
                target: /
            #anonymous: true    
           
         

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
