Umbrella\ShopBundle\Entity\Userproducts:
    type: entity
    repositoryClass: Umbrella\ShopBundle\Repository\UserproductsRepository
    table: userproducts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: userproduct
            joinColumn:
                name: product_id
                referencedColumnName: id   